services:
  frontend:
    container_name: frontend-container
    build:
        context: .
        dockerfile: frontend/Dockerfile
    env_file: ./frontend/.env.production
    expose:
        - 5173

  backend:
    container_name: backend-container
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
        restart: true
    volumes:
        - media_volume:/app/media
    expose:
        - 8000
  
  database:
    container_name: database-container
    image: postgres:17.5-alpine3.22
    restart: always
    secrets:
        - postgres_password
    env_file: .env.postgres
    environment:
        POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
        - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    expose:
        - 5432
    
  nginx:
    container_name: nginx-container
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - media_volume:/app/media
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

secrets:
    postgres_password:
        file: postgres_password.txt

volumes:
    postgres_data:
    media_volume: