services:
  frontend:
    container_name: frontend_container
    build: ./frontend
    ports:
        - "5173:5173"

  backend:
    container_name: backend_container
    build: ./backend
    depends_on:
        - database
    env_file: ./backend/.env
    ports:
        - "8000:8000"
  
  database:
    container_name: database_container
    image: postgres:17.5-alpine3.22
    restart: always
    environment:
        POSTGRES_DB: postgres_db
        POSTGRES_USER: postgres_admin
        POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
        - "5432:5432"
    secrets:
        - db_password
    volumes:
        - db-data:/var/lib/postgresql/data

secrets:
    db_password:
        file: db_password.txt

volumes:
    db-data: